import type { NextPage } from 'next'
import Head from 'next/head'

/**
 * TODO definir slider de fotos
 * TODO rellenar datos de contacto nuevos
 */

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>LIMA Makers</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" type="image/png" href="/white.png" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta charSet="utf-8"/>
      </Head>
      <div>
        
      </div>
    </div>
  )
}

export default Home
